const quizData = [
    { id: 1, q: "What is the form of government of the United States?", a: "Republic / Constitution-based federal republic / Representative democracy" },
    { id: 2, q: "What is the supreme law of the land? *", a: "The Constitution", s: true },
    { id: 3, q: "Name one thing the U.S. Constitution does.", a: "Forms the government / Defines the powers of government / Protects the basic rights of the people" },
    { id: 4, q: "The U.S. Constitution starts with the words \"We the People.\" What does \"We the People\" mean?", a: "Self-government / Popular sovereignty / Consent of the governed" },
    { id: 5, q: "How are changes made to the U.S. Constitution?", a: "Amendments / The amendment process" },
    { id: 6, q: "What does the Bill of Rights protect?", a: "The basic rights of Americans / The basic rights of people living in the United States" },
    { id: 7, q: "How many amendments does the U.S. Constitution have? *", a: "Twenty-seven (27)", s: true },
    { id: 8, q: "Why is the Declaration of Independence important?", a: "It says America is free from British control / It says all people are created equal / It identifies inherent rights / It identifies individual freedoms" },
    { id: 9, q: "What founding document said the American colonies were free from Britain?", a: "Declaration of Independence" },
    { id: 10, q: "Name two important ideas from the Declaration of Independence and the U.S. Constitution.", a: "Equality / Liberty / Social contract / Natural rights / Limited government / Self-government" },
    { id: 11, q: "The words \"Life, Liberty, and the pursuit of Happiness\" are in what founding document?", a: "Declaration of Independence" },
    { id: 12, q: "What is the economic system of the United States? *", a: "Capitalism / Free market economy", s: true },
    { id: 13, q: "What is the rule of law?", a: "Everyone must follow the law / Leaders must obey the law / Government must obey the law / No one is above the law" },
    { id: 14, q: "Many documents influenced the U.S. Constitution. Name one.", a: "Declaration of Independence / Articles of Confederation / Federalist Papers / Anti-Federalist Papers / Virginia Declaration of Rights / Fundamental Orders of Connecticut / Mayflower Compact / Iroquois Great Law of Peace" },
    { id: 15, q: "There are three branches of government. Why?", a: "So one part does not become too powerful / Checks and balances / Separation of powers" },
    {
        id: 16,
        q: "Name the three branches of government.",
        a: "Legislative, executive, and judicial | Congress, president, and the courts"
    },
    { id: 17, q: "The President of the United States is in charge of which branch of government?", a: "Executive branch" },
    { id: 18, q: "What part of the federal government writes laws?", a: "U.S. Congress / U.S. or national legislature / Legislative branch" },
    { id: 19, q: "What are the two parts of the U.S. Congress?", a: "Senate and House of Representatives" },
    { id: 20, q: "Name one power of the U.S. Congress. *", a: "Writes laws / Declares war / Makes the federal budget", s: true },
    { id: 21, q: "How many U.S. senators are there?", a: "One hundred (100)" },
    { id: 22, q: "How long is a term for a U.S. senator?", a: "Six (6) years" },
    { id: 23, q: "Who is one of your state's U.S. senators now? *", a: "Mark Kelly / Ruben Gallego", note: "Arizona Senators", s: true },
    { id: 24, q: "How many voting members are in the House of Representatives?", a: "435" },
    { id: 25, q: "How long is a term for a member of the House of Representatives?", a: "Two (2) years" },
    { id: 26, q: "Why do U.S. representatives serve shorter terms than U.S. senators?", a: "To more closely follow public opinion" },
    { id: 27, q: "How many senators does each state have?", a: "Two (2)" },
    { id: 28, q: "Why does each state have two senators?", a: "Equal representation / The Great Compromise (Connecticut Compromise)" },
    { id: 29, q: "Name your U.S. representative.", a: "Eli Crane / Paul Gosar / Ruben Gallego / Greg Stanton / David Schweikert / Raul Grijalva / Juan Ciscomani / Debbie Lesko / Greg Stanton", note: "Depends on your AZ district", s: false },
    { id: 30, q: "What is the name of the Speaker of the House of Representatives now? *", a: "Mike Johnson", s: true },
    { id: 31, q: "Who does a U.S. senator represent?", a: "Citizens of their state / People of their state" },
    { id: 32, q: "Who elects U.S. senators?", a: "Citizens from their state" },
    { id: 33, q: "Who does a member of the House of Representatives represent?", a: "Citizens in their district / People in their district" },
    { id: 34, q: "Who elects members of the House of Representatives?", a: "Citizens from their district" },
    { id: 35, q: "Some states have more representatives than other states. Why?", a: "The state's population / Because they have more people / Because some states have more people" },
    { id: 36, q: "The President of the United States is elected for how many years? *", a: "Four (4) years", s: true },
    { id: 37, q: "The President of the United States can serve only two terms. Why?", a: "22nd Amendment / To keep the president from becoming too powerful" },
    { id: 38, q: "What is the name of the President of the United States now? *", a: "Donald J. Trump / Donald Trump", s: true },
    { id: 39, q: "What is the name of the Vice President of the United States now? *", a: "JD Vance / James David Vance", s: true },
    { id: 40, q: "If the president can no longer serve, who becomes president?", a: "The Vice President" },
    { id: 41, q: "Name one power of the president.", a: "Signs bills into law / Vetoes bills / Enforces laws / Commander in Chief of the military / Chief diplomat" },
    { id: 42, q: "Who is Commander in Chief of the U.S. military?", a: "The President" },
    { id: 43, q: "Who signs bills to become laws?", a: "The President" },
    { id: 44, q: "Who vetoes bills? *", a: "The President", s: true },
    { id: 45, q: "Who appoints federal judges?", a: "The President" },
    { id: 46, q: "The executive branch has many parts. Name one.", a: "President / Vice President / Cabinet / Federal departments and agencies" },
    { id: 47, q: "What does the President’s Cabinet do?", a: "Advises the President" },
    { id: 48, q: "What are two Cabinet-level positions?", a: "Attorney General / Secretary of Agriculture / Secretary of Commerce / Secretary of Defense / Secretary of Education / Secretary of Energy / Secretary of Health and Human Services / Secretary of Homeland Security / Secretary of Housing and Urban Development / Secretary of the Interior / Secretary of Labor / Secretary of State / Secretary of Transportation / Secretary of the Treasury / Secretary of Veterans Affairs / Vice President" },
    { id: 49, q: "Why is the Electoral College important?", a: "It decides who is elected president / It provides a compromise between the popular election of the president and congressional selection" },
    { id: 50, q: "What is one part of the judicial branch?", a: "Supreme Court / Federal Courts" },
    { id: 51, q: "What does the judicial branch do?", a: "Reviews laws / Explains laws / Resolves disputes / Decides if a law goes against the U.S. Constitution" },
    { id: 52, q: "What is the highest court in the United States? *", a: "Supreme Court", s: true },
    { id: 53, q: "How many seats are on the Supreme Court?", a: "Nine (9)" },
    { id: 54, q: "How many Supreme Court justices are usually needed to decide a case?", a: "Five (5)" },
    { id: 55, q: "How long do Supreme Court justices serve?", a: "For life / Lifetime appointment / Until retirement" },
    { id: 56, q: "Supreme Court justices serve for life. Why?", a: "To be independent of politics / To limit outside political influence" },
    { id: 57, q: "Who is the Chief Justice of the United States now?", a: "John G. Roberts, Jr. / John Roberts" },
    { id: 58, q: "Name one power that is only for the federal government.", a: "Print paper money / Mint coins / Declare war / Create an army / Make treaties / Set foreign policy" },
    { id: 59, q: "Name one power that is only for the states.", a: "Provide schooling and education / Provide protection (police) / Provide safety (fire departments) / Give a driver's license / Approve zoning and land use" },
    { id: 60, q: "What is the purpose of the 10th Amendment?", a: "It states that the powers not given to the federal government belong to the states or to the people." },
    { id: 61, q: "Who is the governor of your state now? *", a: "Katie Hobbs", note: "Arizona Governor", s: true },
    { id: 62, q: "What is the capital of your state?", a: "Phoenix" },
    { id: 63, q: "There are four amendments to the U.S. Constitution about who can vote. Describe one of them.", a: "Citizens 18 and older can vote / You don't have to pay a poll tax to vote / Any citizen can vote / A male citizen of any race can vote" },
    { id: 64, q: "Who can vote in federal elections, run for federal office, and serve on a jury in the United States?", a: "Citizens / United States citizens" },
    { id: 65, q: "What are three rights of everyone living in the United States?", a: "Freedom of expression / Freedom of speech / Freedom of assembly / Freedom to petition the government / Freedom of religion / The right to bear arms" },
    { id: 66, q: "What do we show loyalty to when we say the Pledge of Allegiance? *", a: "The United States / The flag", s: true },
    { id: 67, q: "Name two promises that new citizens make in the Oath of Allegiance.", a: "Give up loyalty to other countries / Defend the U.S. Constitution / Obey the laws of the United States / Serve in the military (if needed) / Serve the nation / Be loyal to the United States" },
    { id: 68, q: "How can people become United States citizens?", a: "Naturalize / Be born in the United States" },
    { id: 69, q: "What are two examples of civic participation in the United States?", a: "Vote / Run for office / Join a political party / Help with a campaign / Join a civic group / Join a community group / Give an elected official your opinion / Call Senators and Representatives / Publicly support or oppose an issue / Write to a newspaper" },
    { id: 70, q: "What is one way Americans can serve their country?", a: "Vote / Pay taxes / Obey the law / Serve in the military / Run for office / Work for local, state, or federal government" },
    { id: 71, q: "Why is it important to pay federal taxes?", a: "Required by law / All people are required to pay by the 16th Amendment / Civic duty" },
    { id: 72, q: "It is important for all men age 18 through 25 to register for the Selective Service. Name one reason why.", a: "Required by law / Civic duty / Makes the draft fair, if needed" },
    { id: 73, q: "Colonists came to America for many reasons. Name one.", a: "Freedom / Political liberty / Religious freedom / Economic opportunity / Escape persecution" },
    { id: 74, q: "Who lived in America before the Europeans arrived? *", a: "American Indians / Native Americans", s: true },
    { id: 75, q: "What group of people was taken to the American colonies and sold as slaves?", a: "Africans / People from Africa" },
    { id: 76, q: "What war did the Americans fight to win independence from Britain?", a: "American Revolution / Revolutionary War / War of American Independence" },
    { id: 77, q: "Name one reason why the Americans declared independence from Britain.", a: "High taxes / Taxation without representation / British army stayed in their houses (boarding, quartering) / They didn't have self-government" },
    { id: 78, q: "Who wrote the Declaration of Independence? *", a: "Thomas Jefferson", s: true },
    { id: 79, q: "When was the Declaration of Independence adopted?", a: "July 4, 1776" },
    { id: 80, q: "The American Revolution had many important events. Name one.", a: "Battle of Bunker Hill / Declaration of Independence / Washington Crossing the Delaware / Battle of Saratoga / Valley Forge / Battle of Yorktown / Treaty of Paris" },
    { id: 81, q: "There were 13 original states. Name five.", a: "New Hampshire / Massachusetts / Rhode Island / Connecticut / New York / New Jersey / Pennsylvania / Delaware / Maryland / Virginia / North Carolina / South Carolina / Georgia" },
    { id: 82, q: "What founding document was written in 1787?", a: "U.S. Constitution" },
    { id: 83, q: "The Federalist Papers supported the passage of the U.S. Constitution. Name one of the writers.", a: "James Madison / Alexander Hamilton / John Jay / Publius" },
    { id: 84, q: "Why were the Federalist Papers important?", a: "They helped people understand the U.S. Constitution / They supported passing the U.S. Constitution" },
    { id: 85, q: "Benjamin Franklin is famous for many things. Name one.", a: "First Postmaster General of the United States / Helped write the Declaration of Independence / Inventor / U.S. diplomat" },
    { id: 86, q: "George Washington is famous for many things. *", a: "Father of Our Country / First president of the United States / General of the Continental Army / President of the Constitutional Convention", s: true },
    { id: 87, q: "Thomas Jefferson is famous for many things.", a: "Writer of the Declaration of Independence / Third president of the United States / Doubled the size of the United States (Louisiana Purchase)" },
    { id: 88, q: "James Madison is famous for many things.", a: "Father of the Constitution / Fourth president of the United States / President during the War of 1812 / One of the writers of the Federalist Papers" },
    { id: 89, q: "Alexander Hamilton is famous for many things.", a: "First Secretary of the Treasury / One of the writers of the Federalist Papers / Helped establish the First Bank of the United States" },
    { id: 90, q: "What territory did the United States buy from France in 1803?", a: "Louisiana Territory / Louisiana" },
    { id: 91, q: "Name one war fought by the United States in the 1800s.", a: "War of 1812 / Mexican-American War / Civil War / Spanish-American War" },
    { id: 92, q: "Name the U.S. war between the North and the South.", a: "The Civil War" },
    { id: 93, q: "The Civil War had many important events. Name one.", a: "Battle of Fort Sumter / Emancipation Proclamation / Battle of Vicksburg / Battle of Gettysburg / Sherman's March / Surrender at Appomattox / Assassination of Abraham Lincoln" },
    { id: 94, q: "Abraham Lincoln is famous for many things. *", a: "Freed the slaves (Emancipation Proclamation) / Saved (or preserved) the Union / President during the Civil War / Gettysburg Address", s: true },
    { id: 95, q: "What did the Emancipation Proclamation do?", a: "Freed the slaves / Freed slaves in the Confederacy / Freed slaves in the Confederate states / Freed slaves in most Southern states" },
    { id: 96, q: "What U.S. war ended slavery?", a: "The Civil War" },
    { id: 97, q: "What amendment to the U.S. Constitution gives citizenship to all persons born in the United States?", a: "14th Amendment" },
    { id: 98, q: "When did all men get the right to vote?", a: "After the Civil War / During Reconstruction / 15th Amendment / 1870" },
    { id: 99, q: "Name one leader of the women’s rights movement in the 1800s.", a: "Susan B. Anthony / Elizabeth Cady Stanton / Sojourner Truth / Harriet Tubman / Lucretia Mott / Lucy Stone" },
    { id: 100, q: "Name one war fought by the United States in the 1900s.", a: "World War I / World War II / Korean War / Vietnam War / Persian Gulf War" },
    { id: 101, q: "Why did the United States enter World War I?", a: "Because Germany attacked U.S. (civilian) ships / To support the Allied Powers (England, France, Italy, and Russia) / To oppose the Central Powers (Germany, Austria-Hungary, the Ottoman Empire, and Bulgaria)" },
    { id: 102, q: "When did all women get the right to vote?", a: "1920 / After World War I / 19th Amendment" },
    { id: 103, q: "What was the Great Depression?", a: "Longest economic recession in modern history" },
    { id: 104, q: "When did the Great Depression start?", a: "The Stock Market Crash of 1929 / Black Tuesday" },
    { id: 105, q: "Who was president during the Great Depression and World War II?", a: "Franklin Roosevelt" },
    { id: 106, q: "Why did the United States enter World War II?", a: "Bombing of Pearl Harbor / Japanese attacked Pearl Harbor / To support the Allied Powers / To oppose the Axis Powers" },
    { id: 107, q: "Dwight Eisenhower is famous for many things.", a: "General during World War II / 34th president of the United States / Signed the Federal Aid Highway Act of 1956 (Interstate Highway System)" },
    { id: 108, q: "Who was the United States’ main rival during the Cold War?", a: "Soviet Union / USSR / Russia" },
    { id: 109, q: "During the Cold War, what was one main concern of the United States?", a: "Communism / Nuclear war" },
    { id: 110, q: "Why did the United States enter the Korean War?", a: "To stop the spread of communism" },
    { id: 111, q: "Why did the United States enter the Vietnam War?", a: "To stop the spread of communism" },
    { id: 112, q: "What did the civil rights movement do?", a: "Fought to end racial discrimination" },
    { id: 113, q: "Martin Luther King, Jr. is famous for many things.", a: "Fought for civil rights / Worked for equality for all Americans / Worked to ensure that people would \"not be judged by the color of their skin, but by the content of their character\"" },
    { id: 114, q: "Why did the United States enter the Persian Gulf War?", a: "To force the Iraqi military from Kuwait" },
    { id: 115, q: "What major event happened on September 11, 2001, in the United States? *", a: "Terrorists attacked the United States / Terrorists took over two planes and crashed them into the World Trade Center in New York City", s: true },
    { id: 116, q: "Name one U.S. military conflict after the September 11, 2001, attacks.", a: "Global War on Terror / War in Afghanistan / War in Iraq" },
    { id: 117, q: "Name one American Indian tribe in the United States.", a: "Apache / Blackfeet / Cayuga / Cherokee / Cheyenne / Chickasaw / Choctaw / Comanche / Crow / Hopi / Huron / Iroquois / Lakota / Navajo / Oneida / Onondaga / Seminole / Seneca / Shawnee / Sioux / Teton / Tuscarora" },
    { id: 118, q: "Name one example of American innovation.", a: "Light bulb / Automobile (cars, internal combustion engine) / Skyscrapers / Airplane / Assembly line / Landing on the moon / Integrated circuit (computer chip)" },
    { id: 119, q: "What is the capital of the United States?", a: "Washington, D.C." },
    { id: 120, q: "Where is the Statue of Liberty?", a: "New York (Harbor) / Liberty Island" },
    { id: 121, q: "Why does the flag have 13 stripes? *", a: "Because there were 13 original colonies / Because the stripes represent the original colonies", s: true },
    { id: 122, q: "Why does the flag have 50 stars?", a: "Because there is one star for each state / Because each star represents a state / Because there are 50 states" },
    { id: 123, q: "What is the name of the national anthem?", a: "The Star-Spangled Banner" },
    { id: 124, q: "The Nation's first motto was \"E Pluribus Unum.\" What does that mean?", a: "Out of many, one / We all become one" },
    { id: 125, q: "What is Independence Day?", a: "A holiday to celebrate U.S. independence (from Britain) / The country’s birthday" },
    { id: 126, q: "Name three national U.S. holidays.", a: "New Year's Day / Martin Luther King, Jr. Day / Presidents Day / Memorial Day / Juneteenth / Independence Day / Labor Day / Columbus Day / Veterans Day / Thanksgiving Day / Christmas Day" },
    { id: 127, q: "What is Memorial Day?", a: "A holiday to honor soldiers who died in military service" },
    { id: 128, q: "What is Veterans Day?", a: "A holiday to honor people in the (U.S.) military / A holiday to honor people who have served in the (U.S.) military" }
];